---
name: Labeler

on:
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: "ubuntu-latest"
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-token
        with:
          app_id: ${{ secrets.RIVERBOT_APP_ID }}
          private_key: ${{ secrets.RIVERBOT_APP_PRIVATE_KEY }}

      - name: Labeler
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4
        with:
          repo-token: "${{ steps.generate-token.outputs.token }}"
          configuration-path: .github/labeler.yaml
      
      - name: Label Size
        uses: pascalgn/size-label-action@37a5ad4ae20ea8032abf169d953bcd661fd82cd3 # v0.5.0
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
