---
name: Labeler

on:
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: "ubuntu-latest"
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@46e4a501e119d39574a54e53a06c9a705efc55c9 # v1.6.1
        with:
          app-id: ${{ secrets.RIVERBOT_APP_ID }}
          private-key: ${{ secrets.RIVERBOT_APP_PRIVATE_KEY }}

      - name: Labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: "${{ steps.generate-token.outputs.token }}"
          configuration-path: .github/labeler.yaml
      
      - name: Label Size
        uses: pascalgn/size-label-action@37a5ad4ae20ea8032abf169d953bcd661fd82cd3 # v0.5.0
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }
